- name: Create lab environment
  hosts: localhost
  connection: local
  tasks:
  - name: Create ssh folder in cloudshell
    file:
      path: ~/.ssh
      state: directory
  - name: Generate SSH keys
    openssh_keypair:
      path: ~/.ssh/lab_rsa
  - name: Copy SSH config to localhost
    copy:
      src: ssh.config/ssh.config
      dest: ~/.ssh/config
  - name: Get my public IP
    ipify_facts:
      timeout: 20
    delegate_to: localhost
  - name: output cloudshell public_ip
    debug: msg="my cloudshell public ip is {{ ipify_public_ip }}"
  
  - name: Terraform apply
    terraform:
      lock: no
      force_init: true
      provider_upgrade: true
      variables:
        cloudshell_public_ip: "{{ ipify_public_ip }}"
      project_path: './'
      state: present